name: sls-deploy
description: Deploy Serverless Application

inputs:
  stage:
    required: true
  node-env:
    required: true
  vars:
    required: true
  secrets:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Export Environment Variables
      shell: bash
      run: |
        echo "${{ inputs.vars }}" > vars.json
        echo "${{ inputs.secrets }}" > secrets.json

        for key in $(jq -r 'keys[]' vars.json); do
          value=$(jq -r ".\"$key\"" vars.json)
          echo "$key=$value" >> $GITHUB_ENV
        done

        for key in $(jq -r 'keys[]' secrets.json); do
          value=$(jq -r ".\"$key\"" secrets.json)
          echo "$key=$value" >> $GITHUB_ENV
        done

    - name: Deploy Application
      shell: bash
      env:
        NODE_ENV: ${{ inputs.node-env }}
        STAGE: ${{ inputs.stage }}
        SLS_DEBUG: '*'
      run: |
        npm run deploy -- --stage ${{ inputs.stage }}
