name: serverless-deploy

inputs:
  stage:
    required: true
  node-env:
    required: true
  vars:
    required: true
  secrets:
    required: true

runs:
  using: composite
  steps:
    - name: Deploy Application
      shell: bash
      env:
        NODE_ENV: ${{ inputs.node-env }}
        STAGE: ${{ inputs.stage }}
        SLS_DEBUG: '*'
        AUTH_ENCRYPTION_KEY: ${{ fromJson(inputs.secrets).AUTH_ENCRYPTION_KEY }}
        AUTH_ENCRYPTION_SALT: ${{ fromJson(inputs.secrets).AUTH_ENCRYPTION_SALT }}
        AUTH_HMAC_KEY: ${{ fromJson(inputs.secrets).AUTH_HMAC_KEY }}
        AUTH_SERVICE_URL: ${{ fromJson(inputs.vars).AUTH_SERVICE_URL }}
        AWS_ACCOUNT_ID: ${{ fromJson(inputs.secrets).AWS_ACCOUNT_ID }}
        DB_HOST: ${{ fromJson(inputs.secrets).DB_HOST }}
        DB_MAX_CONNECTIONS: ${{ fromJson(inputs.vars).DB_MAX_CONNECTIONS }}
        DB_NAME: ${{ fromJson(inputs.secrets).DB_NAME }}
        DB_PASSWORD: ${{ fromJson(inputs.secrets).DB_PASSWORD }}
        DB_PORT: ${{ fromJson(inputs.secrets).DB_PORT }}
        DB_PROXY_ENABLED: ${{ fromJson(inputs.vars).DB_PROXY_ENABLED }}
        DB_TLS_DISABLED: ${{ fromJson(inputs.vars).DB_TLS_DISABLED }}
        DB_USER: ${{ fromJson(inputs.secrets).DB_USER }}
        JWT_ISSUER: ${{ fromJson(inputs.secrets).JWT_ISSUER }}
        LOG_LEVEL: ${{ fromJson(inputs.vars).LOG_LEVEL }}
        REDIS_HOST: ${{ fromJson(inputs.secrets).REDIS_HOST }}
        REDIS_PORT: ${{ fromJson(inputs.secrets).REDIS_PORT }}
        REDIS_AUTH_TOKEN: ${{ fromJson(inputs.secrets).REDIS_AUTH_TOKEN }}
        SMTP_AUTH_EMAIL: ${{ fromJson(inputs.secrets).SMTP_AUTH_EMAIL }}
        SMTP_HOST: ${{ fromJson(inputs.secrets).SMTP_HOST }}
        SMTP_USERNAME: ${{ fromJson(inputs.secrets).SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ fromJson(inputs.secrets).SMTP_PASSWORD }}
        VPC_SECURITY_GROUP_IDS: ${{ fromJson(inputs.secrets).VPC_SECURITY_GROUP_IDS }}
        VPC_SUBNET_IDS: ${{ fromJson(inputs.secrets).VPC_SUBNET_IDS }}
      run: |
        npm run deploy -- --stage ${{ inputs.stage }}
