service: relaybox-auth

plugins:
  - serverless-offline

package:
  individually: true

variablesResolutionMode: 20210326

custom:
  serverless-offline:
    httpPort: 4005
    lambdaPort: 3005
    reloadHandler: true
    location: 'build'
    noPrependStageInUrl: true

  keepAlive:
    eventBridge:
      schedule: rate(5 minutes)
      enabled: true
      input:
        keepAlive: true

  cors:
    origin: '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Ds-Client-Id
      - X-Ds-Connection-Id
      - X-Ds-Public-Key
    allowCredentials: true

  vars:
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS, ''}
    AUTH_ENCRYPTION_KEY: ${env:AUTH_ENCRYPTION_KEY, ''}
    AUTH_ENCRYPTION_SALT: ${env:AUTH_ENCRYPTION_SALT, ''}
    AUTH_HMAC_KEY: ${env:AUTH_HMAC_KEY, ''}
    AUTH_SERVICE_URL: ${env:AUTH_SERVICE_URL, ''}
    AUTO_VERIFY: ${env:AUTO_VERIFY, ''}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID, ''}
    DB_HOST: ${env:DB_HOST, ''}
    DB_MAX_CONNECTIONS: ${env:DB_MAX_CONNECTIONS, ''}
    DB_NAME: ${env:DB_NAME, ''}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_PORT: ${env:DB_PORT, ''}
    DB_PROXY_ENABLED: ${env:DB_PROXY_ENABLED, ''}
    DB_TLS_DISABLED: ${env:DB_TLS_DISABLED, ''}
    DB_USER: ${env:DB_USER, ''}
    JWT_ISSUER: ${env:JWT_ISSUER, ''}
    LOG_LEVEL: ${env:LOG_LEVEL, ''}
    SMTP_AUTH_EMAIL: ${env:SMTP_AUTH_EMAIL, ''}
    SMTP_HOST: ${env:SMTP_HOST, ''}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD, ''}
    SMTP_USERNAME: ${env:SMTP_USERNAME, ''}
    PUBLIC_URL: ${env:PUBLIC_URL, ''}
    NODE_ENV: ${env:NODE_ENV, 'production'}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 3008
  environment: ${self:custom.vars}
  stage: ${opt:stage, env:STAGE, 'dev'}
  timeout: 300

functions:
  - ${file(./functions/validation.yml)}
  - ${file(./functions/users.yml)}
