name: Deploy development

on:
  push:
    branches:
      - main
      - feature/20240924_deployment_refactor_v2

jobs:
  deploy:
    name: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/relaybox-${{ vars.STAGE }}-DeployerRole
          role-session-name: gha_deployer
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Dependencies
        run: npm ci

      - name: Deploy Application
        uses: ./.github/actions/sls-deploy
        with:
          stage: ${{ vars.STAGE }}
          node-env: ${{ vars.NODE_ENV }}
          vars: ${{ toJson(vars) }}
          secrets: ${{ toJson(secrets) }}
