on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      db-user:
        required: true
        type: string
      db-name:
        required: true
        type: string
      db-host:
        required: true
        type: string

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ inputs.db-user }}
          POSTGRES_DB: ${{ inputs.db-name }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout relaybox-db repository
        uses: actions/checkout@v4
        with:
          repository: relaybox/relaybox-db
          ssh-key: ${{ secrets.X_REPO_PRIVATE_SSH_KEY }}
          ref: main
          sparse-checkout: |
            db
          path: relaybox-db

      - name: list files
        run: |
          cd relaybox-db
          ls -al

      - name: Restore database
        run: |
          psql -h ${{ inputs.db-host }} -p 5433 -U ${{ inputs.db-user }} -d ${{ inputs.db-name }} -f relaybox-db/db/schema.sql

      - name: Verify database restoration
        run: |
          psql -h ${{ inputs.db-host }} -p 5433 -U ${{ inputs.db-user }} -d ${{ inputs.db-name }} -c "\dt"

      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
